name: Check PO Glossary

on:
  pull_request:
    types: [opened, synchronize] # 在 PR 開啟或更新時觸發
    paths:
      - '**.po' # 只在 .po 檔案有變動時才執行

jobs:
  check-glossary:
    runs-on: ubuntu-latest
    # 需要權限來讀取內容和寫入 PR 評論/建議
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # 獲取完整的 git 歷史，以便比較檔案
          fetch-depth: 0

      - name: Get changed PO files
        id: changed-files
        uses: tj-actions/changed-files@v44 # 使用一個 action 來找出變動的檔案
        with:
          files: |
            **.po

      - name: Set up Python
        if: steps.changed-files.outputs.any_changed == 'true' # 只有在 PO 檔有變動時才繼續
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install polib requests

      - name: Run glossary check script
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          # 將需要的資訊傳遞給 Python 腳本
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.number }}
          COMMIT_ID: ${{ github.event.pull_request.head.sha }}
        run: |
          python .github/scripts/check_glossary.py .github/glossary.json ${{ steps.changed-files.outputs.all_changed_files }}