name: Glossary Suggestion Check

on:
  pull_request:
    paths:
      - '**.po'

jobs:
  glossary-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install polib
          sudo apt-get install -y gh

      - name: Run glossary check and suggest corrections
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
        run: python scripts/check_glossary_suggest.py